import React, { useEffect, useState, useMemo } from 'react';
import axios from '../../api/axios';
import DataTable from '../common/DataTable';
import { UserPlusIcon, TrashIcon, PencilSquareIcon, CheckIcon, XMarkIcon, MagnifyingGlassIcon } from '@heroicons/react/24/outline';
import ClassFormModal from './ClassFormModal';
import ConfirmationModal from '../common/ConfirmationModal';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { saveAs } from 'file-saver';
import { Document, Packer, Paragraph, Table, TableCell, TableRow, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { useNavigate } from 'react-router-dom';

const ClassList = () => {
  const [classes, setClasses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [search, setSearch] = useState('');
  const [modalOpen, setModalOpen] = useState(false);
  const [modalData, setModalData] = useState(null);
  const [editId, setEditId] = useState(null);
  const [editName, setEditName] = useState('');
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [classToDelete, setClassToDelete] = useState(null);
  const navigate = useNavigate();

  const fetchClasses = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await axios.get('/classes');
      setClasses(response.data);
    } catch (err) {
      console.error('Error fetching classes:', err);
      if (err.response && err.response.data && err.response.data.message) {
        setError('Failed to fetch classes: ' + err.response.data.message);
      } else if (err.message) {
        setError('Failed to fetch classes: ' + err.message);
      } else {
        setError('Failed to fetch classes.');
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchClasses();
  }, []);

  const handleAddClass = () => {
    setModalData(null);
    setModalOpen(true);
  };

  const handleEditClass = (cls) => {
    setModalData({
      id: cls.id,
      name: cls.name,
      teacherIds: cls.teachers ? cls.teachers.map(t => t.id) : []
    });
    setModalOpen(true);
  };

  const handleDeleteClick = (cls) => {
    setClassToDelete(cls);
    setConfirmOpen(true);
  };

  const handleConfirmDelete = async () => {
    if (!classToDelete) return;
    setLoading(true);
    setError('');
    setSuccess('');
    try {
      await axios.delete(`/classes/${classToDelete.id}`);

      fetchClasses();
      setConfirmOpen(false);
      setClassToDelete(null);
    } catch (err) {
      if (err.response && err.response.status === 409) {
        setError('Cannot delete class: remove related records (e.g., students) first.');
      } else {
        setError('Failed to delete class.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (cls, type) => {
    try {
      const res = await axios.get(`/classes/${cls.id}/students`);
      const students = res.data;
      const schoolHeader = 'Your School Name\nAddress Line 1, City, Country\nPhone: 123-456-7890';
      const schoolFooter = 'Generated by School Management System';
      const classTitle = `Class: ${cls.name}`;
      const dateStr = new Date().toLocaleDateString();
      // Table columns
      const columns = [
        { header: 'No.', dataKey: 'no' },
        { header: 'Name', dataKey: 'name' },
        { header: 'Gender', dataKey: 'gender' },
        { header: 'Phone', dataKey: 'phone' },
        { header: 'Address', dataKey: 'address' },
      ];
      const rows = students.map((s, i) => ({
        no: i + 1,
        name: `${s.firstName} ${s.lastName}`,
        gender: s.gender || '',
        phone: s.phone || '',
        address: s.address || '',
      }));
      if (type === 'pdf') {
        const doc = new jsPDF();
        doc.setFontSize(14);
        doc.text(schoolHeader, 14, 18);
        doc.setFontSize(12);
        doc.text(classTitle, 14, 32);
        doc.autoTable({
          startY: 38,
          head: [columns.map(c => c.header)],
          body: rows.map(r => columns.map(c => r[c.dataKey])),
          theme: 'grid',
          headStyles: { fillColor: [49, 46, 129] },
          styles: { fontSize: 10 },
        });
        doc.setFontSize(10);
        doc.text(schoolFooter, 14, doc.internal.pageSize.height - 10);
        doc.save(`${cls.name.replace(/\s+/g, '_')}_students.pdf`);
      } else if (type === 'docx') {
        const tableRows = [
          new TableRow({
            children: columns.map(col => new TableCell({
              children: [new Paragraph({ text: col.header, bold: true })],
            })),
          }),
          ...rows.map(r => new TableRow({
            children: columns.map(col => new TableCell({
              children: [new Paragraph(r[col.dataKey] + '')],
            })),
          })),
        ];
        const doc = new Document({
          sections: [{
            properties: {},
            children: [
              new Paragraph({
                text: 'Your School Name',
                heading: HeadingLevel.HEADING_1,
                alignment: AlignmentType.CENTER,
              }),
              new Paragraph({
                text: 'Address Line 1, City, Country',
                alignment: AlignmentType.CENTER,
              }),
              new Paragraph({
                text: 'Phone: 123-456-7890',
                alignment: AlignmentType.CENTER,
              }),
              new Paragraph({ text: '' }),
              new Paragraph({
                text: classTitle,
                heading: HeadingLevel.HEADING_2,
                alignment: AlignmentType.LEFT,
              }),
              new Paragraph({ text: '' }),
              new Table({ rows: tableRows }),
              new Paragraph({ text: '' }),
              new Paragraph({
                text: schoolFooter,
                alignment: AlignmentType.LEFT,
              }),
              new Paragraph({
                text: `Date: ${dateStr}`,
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }],
        });
        Packer.toBlob(doc).then(blob => {
          saveAs(blob, `${cls.name.replace(/\s+/g, '_')}_students.docx`);
        });
      }
    } catch (err) {
      setError('Failed to download students list.');
    }
  };

  const filteredClasses = useMemo(() =>
    classes.filter(cls => cls.name.toLowerCase().includes(search.toLowerCase())),
    [classes, search]
  );

  const columns = useMemo(() => [
    {
      header: 'Class Name',
      accessor: 'name',
      render: (cls) => (
        <span
          className="text-indigo-700 font-semibold cursor-pointer hover:underline"
          onClick={() => navigate(`/classes/${cls.id}`)}
        >
          {cls.name}
        </span>
      ),
    },
    {
      header: 'Teachers',
      accessor: 'teacherIds',
      render: (cls) =>
        cls.teachers && cls.teachers.length > 0
          ? cls.teachers.map(t => `${t.firstName} ${t.lastName}`).join(', ')
          : <span className="text-gray-400 italic">Not assigned</span>
    },
    {
      header: 'Actions',
      render: (cls) => (
        <div className="flex gap-2">
          <button
            onClick={() => handleEditClass(cls)}
            className="p-1.5 rounded text-indigo-600 hover:bg-indigo-100"
            disabled={loading}
            title="Edit"
          >
            <PencilSquareIcon className="h-5 w-5" />
          </button>
          <button
            onClick={() => handleDeleteClick(cls)}
            className="p-1.5 rounded text-red-600 hover:bg-red-100"
            disabled={loading}
            title="Delete"
          >
            <TrashIcon className="h-5 w-5" />
          </button>
        </div>
      ),
    },
  ], [loading, navigate]);

  const tableActions = (
    <div className="flex items-center gap-4 justify-end w-full">
      <div className="relative">
        <MagnifyingGlassIcon className="pointer-events-none absolute inset-y-0 left-3 h-full w-5 text-gray-400" />
        <input
          type="text"
          placeholder="Search classes..."
          className="block w-full rounded-md border-0 py-1.5 pl-10 text-gray-900 dark:text-white dark:bg-gray-700/50 ring-1 ring-inset ring-gray-300 dark:ring-gray-600 focus:ring-2 focus:ring-inset focus:ring-indigo-600"
          value={search}
          onChange={e => setSearch(e.target.value)}
        />
      </div>
      <button
        onClick={handleAddClass}
        className="flex items-center gap-x-1.5 bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg font-semibold shadow-sm"
        disabled={loading}
      >
        <UserPlusIcon className="h-5 w-5" /> Add Class
      </button>
    </div>
  );

  return (
    <div className="w-full max-w-full overflow-x-auto">
      {error && <div className="text-red-500 mb-2">{error}</div>}
      {success && <div className="text-green-600 mb-2">{success}</div>}
      <DataTable
        title="Class Management"
        columns={columns}
        data={filteredClasses}
        loading={loading}
        error={null}
        actions={tableActions}
      />
      <ClassFormModal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        onSuccess={fetchClasses}
        initialData={modalData}
      />
      <ConfirmationModal
        isOpen={confirmOpen}
        onClose={() => { setConfirmOpen(false); setClassToDelete(null); }}
        onConfirm={handleConfirmDelete}
        title="Delete Class"
        message={classToDelete ? `Are you sure you want to delete the class "${classToDelete.name}"? This action cannot be undone.` : ''}
        loading={loading}
      />
    </div>
  );
};

export default ClassList; 